// <auto-generated />
using ClearBank.DeveloperTest.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClearBank.DeveloperTest.Infrastructure.Migrations
{
    [DbContext(typeof(ClearBankContext))]
    [Migration("20251129233624_Initialise")]
    partial class Initialise
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClearBank.DeveloperTest.Core.Models.Account", b =>
                {
                    b.Property<string>("AccountNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AllowedPaymentSchemes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 2)")
                        .HasDefaultValue(0.00m);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AccountNumber");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            AccountNumber = "94202716",
                            AllowedPaymentSchemes = "FasterPayments",
                            Balance = 63254.88m,
                            Status = "Live"
                        },
                        new
                        {
                            AccountNumber = "45302248",
                            AllowedPaymentSchemes = "Bacs",
                            Balance = 21098.76m,
                            Status = "Live"
                        },
                        new
                        {
                            AccountNumber = "09773439",
                            AllowedPaymentSchemes = "Chaps",
                            Balance = 3109.87m,
                            Status = "Live"
                        },
                        new
                        {
                            AccountNumber = "57047920",
                            AllowedPaymentSchemes = "3",
                            Balance = 2678.90m,
                            Status = "Live"
                        },
                        new
                        {
                            AccountNumber = "23992701",
                            AllowedPaymentSchemes = "5",
                            Balance = 89012.34m,
                            Status = "Live"
                        },
                        new
                        {
                            AccountNumber = "31022756",
                            AllowedPaymentSchemes = "6",
                            Balance = 56789.01m,
                            Status = "Live"
                        },
                        new
                        {
                            AccountNumber = "55694617",
                            AllowedPaymentSchemes = "7",
                            Balance = 43210.98m,
                            Status = "Live"
                        },
                        new
                        {
                            AccountNumber = "08845741",
                            AllowedPaymentSchemes = "0",
                            Balance = 32987.65m,
                            Status = "Live"
                        },
                        new
                        {
                            AccountNumber = "65015197",
                            AllowedPaymentSchemes = "3",
                            Balance = 8432.10m,
                            Status = "Disabled"
                        },
                        new
                        {
                            AccountNumber = "99636544",
                            AllowedPaymentSchemes = "7",
                            Balance = 58327.56m,
                            Status = "Disabled"
                        },
                        new
                        {
                            AccountNumber = "14653248",
                            AllowedPaymentSchemes = "FasterPayments",
                            Balance = -250.50m,
                            Status = "InboundPaymentsOnly"
                        },
                        new
                        {
                            AccountNumber = "36946349",
                            AllowedPaymentSchemes = "Bacs",
                            Balance = -750.25m,
                            Status = "InboundPaymentsOnly"
                        },
                        new
                        {
                            AccountNumber = "74000307",
                            AllowedPaymentSchemes = "7",
                            Balance = -1500.75m,
                            Status = "InboundPaymentsOnly"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
